AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 instance

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-0427090fd1714168b' # Amazon Linux 2 AMI (replace with the latest AMI ID for your region)

Outputs:
  InstanceId:
    Description: 'InstanceId of the newly created EC2 instance'
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: 'Public IP address of the newly created EC2 instance'
    Value: !GetAtt MyEC2Instance.PublicIp
